export const FETCH_BOOK_LIST = 'FETCH_BOOK_LIST';
export const CLEAR_BOOK_LIST = 'CLEAR_BOOK_LIST';
export const FILTER_BOOK_LIST_BY_AUTHOR_AVAILABILITY = 'FILTER_BOOK_LIST_BY_AUTHOR_AVAILABILITY';
export const FILTER_BOOK_LIST_BY_COVER_AVAILABILITY = 'FILTER_BOOK_LIST_BY_COVER_AVAILABILITY';
export const FILTER_BOOK_LIST_BY_YEAR_AVAILABILITY = 'FILTER_BOOK_LIST_BY_YEAR_AVAILABILITY';
export const FILTER_BOOK_LIST_BY_YEAR_RANGE = 'FILTER_BOOK_LIST_BY_YEAR_RANGE';
export const FILTER_BOOK_LIST_BY_SUBJECTS = 'FILTER_BOOK_LIST_BY_SUBJECTS';